require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'


platform :ios, '10.0'

target 'Nyxo' do
	pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true



	pod 'OpenSSL-Universal'
	pod 'Intercom'
  use_unimodules!(exclude: ['expo-face-detector'])
	use_flipper!


	target 'NyxoTests' do
    inherit! :complete
    # Pods for testing
  end

	config = use_native_modules!
	use_react_native!(:path => config["reactNativePath"]) 
end 



