require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true
pod 'RNSha256', :path => '../node_modules/react-native-sha256'
pod 'Firebase/Core', '~> 6.9.0'
pod 'Firebase/Messaging', '~> 6.9.0'
pod 'OpenSSL-Universal'



config = use_native_modules!
use_react_native!(:path => config["reactNativePath"]) 

platform :ios, '10.0'
target 'Nyxo' do

	pod 'Intercom'
  use_unimodules!(exclude: ['expo-face-detector'])
  use_native_modules!

  use_flipper!

end 


# target 'Nyxo Dev' do

# pod 'Intercom', '~> 6.0.0'
# pod 'AppAuth', '>= 1.2.0'
# use_unimodules!(exclude: ['expo-face-detector'])
# use_native_modules!

# post_install do |installer|

# installer.pods_project.targets.each do |target|

#   if target.name == 'YogaKit'
#     target.build_configurations.each do |config|
#       config.build_settings['SWIFT_VERSION'] = '4.1'
#     end
#   end

#   if target.name == 'react-native-config'
#     phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
#     phase.shell_script = "cd ../../"\
#     " && RNC_ROOT=./node_modules/react-native-config/"\
#     " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
#     " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb"
    
#     target.build_phases << phase
#     target.build_phases.move(phase,0)
#   end
# end
# end
# end 

